apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: proseed
spec:
  replicas: 1 #replicas 2개 이상부터는 initContainer의 마이그레이션 중복 위험 있음
  selector: #TODO: 마이그레이션 방식 initContainer -> workflow 대체
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
        - name: prisma-migrate
          image: ghcr.io/skkuding/proseed/api:latest
          command: ['npx', 'prisma', 'migrate', 'deploy']
          envFrom:
            - secretRef:
                name: database-credentials
      containers:
        - name: api
          image: ghcr.io/skkuding/proseed/api:latest
          ports:
            - containerPort: 4000
          livenessProbe:
            httpGet:
              path: /api/health
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 0.2
              memory: 200Mi
          envFrom:
            - configMapRef:
                name: api-env
            - secretRef:
                name: database-credentials
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: proseed-aws-credentials
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: proseed-aws-credentials
                  key: aws_secret_access_key
