apiVersion: batch/v1
kind: Job
metadata:
  name: proseed-migrate
  namespace: proseed
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: '1'
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 300
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: proseed-migrate
          image: ghcr.io/skkuding/proseed/api:latest
          workingDir: /app/apps/api
          command: ['npx', 'prisma', 'migrate', 'deploy', '--schema', 'prisma/schema.prisma']
          envFrom:
            - secretRef:
                name: database-credentials
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
