// app/layout.tsx
import type { Metadata } from 'next'
import './globals.css'
import localFont from 'next/font/local'
import { Header } from '@/app/main/_components/Header'
import { Footer } from '@/app/main/_components/Footer'

const pretendard = localFont({
  src: '../font/PretendardVariable.woff2',
  display: 'swap',
  weight: '100 900',
  variable: '--font-pretendard',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={pretendard.variable}>
      <body className={`${pretendard.className} bg-background-normal`}>
        <Header />
        <div className="mx-auto max-w-310 px-10">{children}</div>
        <Footer />
      </body>
    </html>
  )
}
