apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/environment: stage
    spec:
      containers:
        - name: postgres
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: '1'
              memory: 1Gi
