apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: proseed-stage

resources:
  - ../../base
  - db-credentials.yaml
  - namespace.yaml

patches:
  - path: deployment-patch.yaml
  - path: pvc-patch.yaml
