apiVersion: v1
kind: Namespace
metadata:
  name: proseed-stage
  annotations:
    argocd.argoproj.io/sync-wave: '-2'
  labels:
    app.kubernetes.io/name: proseed
    app.kubernetes.io/environment: stage
