apiVersion: v1
kind: ConfigMap
metadata:
  name: web-env
  namespace: proseed
data:
  NEXT_URL: 'https://proseednow.com'
  MEDIA_BUCKET_NAME: 'proseed-media'
  OTEL_EXPORTER_OTLP_ENDPOINT: 'https://otel.proseednow.com'
