apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: proseed-stage

resources:
  - ../../base
  - certificate.yaml
  - noindex-middleware.yaml

patches:
  - path: configmap-patch.yaml
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: web-ingress

images:
  - name: ghcr.io/skkuding/proseed/web
    newTag: stage
