/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["StorageController_checkHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["StorageController_getUploadUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage/download-url/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["StorageController_getDownloadUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["StorageController_deleteFile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserController_checkIsNewUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/nickname": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserController_generateRandomNickname"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["UserController_onboarding"];
        trace?: never;
    };
    "/user/profile/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 다른 팀원의 공개 프로필 미리보기를 이메일 주소를 통해 조회합니다. */
        get: operations["UserController_getProfilePreviewByEmail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{userId}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 다른 팀원의 공개 프로필을 조회합니다. (접근 경로: 프로젝트 상세) */
        get: operations["UserController_getOtherUserProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{userId}/profile/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 다른 팀원의 공개 프로필에서 참여중인 프로젝트 목록을 조회합니다. */
        get: operations["UserController_getOtherUserJoinedProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MypageController_getMyProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["MypageController_updateMyProfile"];
        trace?: never;
    };
    "/me/profile/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MypageController_getMyJoinedProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/profile/feedbacks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MypageController_getMyFeedbacks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project/{projectId}/versions/{versionId}/feedbacks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FeedbackController_findFeedbacksForVersion"];
        put?: never;
        post: operations["FeedbackController_createFeedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project/{projectId}/versions/{versionId}/feedbackQuestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FeedbackController_findAllQuestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedbacks/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MyFeedbackController_getRecentFeedbacks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedbacks/my/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MyFeedbackController_findMyFeedbackProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedbacks/{submissionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MyFeedbackController_findFeedbackSubmissionDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProjectController_getProjects"];
        put?: never;
        post: operations["ProjectController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProjectController_getMyProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProjectController_getProjectById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["ProjectController_update"];
        trace?: never;
    };
    "/project/{id}/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ProjectController_inviteCollaborator"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project/{id}/thumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProjectController_getThumbnail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProjectController_getProjectVersions"];
        put?: never;
        post: operations["GrowthRecordController_createVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project/{id}/versions/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GrowthRecordController_getVersionDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/growth-records/feedback-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GrowthRecordTemplateController_getFeedbackTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/growth-records/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GrowthRecordTemplateController_getRecentGrowthRecords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project/{id}/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GrowthRecordDraftController_getDrafts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project/{id}/drafts/{category}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GrowthRecordDraftController_getDraft"];
        put: operations["GrowthRecordDraftController_upsertDraft"];
        post?: never;
        delete: operations["GrowthRecordDraftController_deleteDraft"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponseDto: Record<string, never>;
        BucketStatusResponseDto: {
            bucket: string;
            status: string;
            objectCount: number;
        };
        GetUploadUrlDto: Record<string, never>;
        UploadUrlResponseDto: {
            /** @description presigned upload URL (PUT 대상) */
            url: string;
            /** @description DB에 저장할 S3 object key */
            key: string;
        };
        DownloadUrlResponseDto: {
            /** @description presigned download URL */
            url: string;
        };
        UserCheckResponseDto: {
            /** @description 온보딩(jobType 설정) 미완료 여부 */
            isNewUser: boolean;
            nickname: string;
        };
        NicknameResponseDto: {
            nickname: string;
        };
        OnboardingDto: {
            /** @enum {string} */
            jobType: "Developer" | "Planner" | "Designer" | "Other";
            nickname: string;
        };
        /** @enum {string} */
        JobType: "Planner" | "Designer" | "Developer" | "Other";
        /** @enum {string} */
        UserRole: "Sprout" | "Seeder";
        UserResponseDto: {
            jobType: components["schemas"]["JobType"] | null;
            userRole: components["schemas"]["UserRole"];
            bio: string | null;
            id: number;
            name: string;
            email: string;
            emailVerified: boolean;
            profileImageUrl: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            ownedTicketCount: number;
            skills: string[];
            links: string[];
        };
        ProfilePreviewResponseDto: {
            jobType: components["schemas"]["JobType"] | null;
            name: string;
        };
        MyProfileAccountDto: {
            providerId: string;
        };
        OtherUserProfileResponseDto: {
            accounts: components["schemas"]["MyProfileAccountDto"][];
            jobType: components["schemas"]["JobType"] | null;
            bio: string | null;
            id: number;
            name: string;
            email: string;
            profileImageUrl: string;
            skills: string[];
            links: string[];
            joinedProjectCount: number;
            feedbackCount: number;
        };
        /** @enum {string} */
        ProjectMemberRole: "Lead" | "TeamLeader" | "TeamMember";
        MypageJoinedProjectListDto: {
            role: components["schemas"]["JobType"];
            projectMemberRole: components["schemas"]["ProjectMemberRole"];
            id: number;
            title: string;
            oneLineDescription: string;
            iconUrl: string;
        };
        MyProfileResponseDto: {
            accounts: components["schemas"]["MyProfileAccountDto"][];
            jobType: components["schemas"]["JobType"] | null;
            bio: string | null;
            name: string;
            email: string;
            profileImageUrl: string;
            skills: string[];
            links: string[];
            ownedTicketCount: number;
            joinedProjectCount: number;
            feedbackCount: number;
        };
        MypageUpdateDto: {
            name?: string;
            /** @enum {string} */
            jobType?: "Developer" | "Planner" | "Designer" | "Other";
            profileImageUrl?: string;
            skills?: string[];
            links?: string[];
            bio?: string;
        };
        MyProfileUpdateResponseDto: {
            jobType: components["schemas"]["JobType"] | null;
            bio: string | null;
            name: string;
            profileImageUrl: string;
            skills: string[];
            links: string[];
        };
        MyFeedbackProjectItemDto: {
            submissionId: number;
            versionId: number;
            projectId: number;
            projectTitle: string;
            projectIconUrl: string;
            oneLineDescription: string;
            isAdopted: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        MyFeedbackProjectsResponseDto: {
            success: boolean;
            data: components["schemas"]["MyFeedbackProjectItemDto"][];
        };
        FeedbackItemDto: {
            questionId: number;
            content: string;
            imageUrl?: string;
            imageUrls?: string[];
        };
        CreateFeedbackDto: {
            oneLineReview: string;
            feedbacks: components["schemas"]["FeedbackItemDto"][];
        };
        CreatedFeedbackDto: {
            imageUrl: string | null;
            imageUrls: string[];
            id: number;
            questionId: number;
            versionId: number;
            userId: number;
            content: string;
            /** Format: date-time */
            createdAt: string;
        };
        CreateFeedbackDataDto: {
            submittedCount: number;
            feedbacks: components["schemas"]["CreatedFeedbackDto"][];
        };
        CreateFeedbackResponseDto: {
            success: boolean;
            data: components["schemas"]["CreateFeedbackDataDto"];
        };
        /** @enum {string} */
        RecordCategory: "PLAN" | "DESIGN" | "DEVELOPMENT" | "GENERAL";
        FeedbackQuestionItemDto: {
            category: components["schemas"]["RecordCategory"];
            id: number;
            title: string;
            description: string;
            order: number;
            required: boolean;
        };
        FeedbackQuestionsResponseDto: {
            success: boolean;
            data: components["schemas"]["FeedbackQuestionItemDto"][];
        };
        FeedbackSubmissionAuthorDto: {
            role: components["schemas"]["JobType"] | null;
            name: string;
            profileImageUrl: string;
        };
        FeedbackListItemDto: {
            category: components["schemas"]["RecordCategory"];
            imageUrls: string[];
            submissionId: number;
            userId: number;
            author: components["schemas"]["FeedbackSubmissionAuthorDto"];
            oneLineReview: string;
            /** @description 이미 다른 성장기록에 채택(태그)된 제출인지 — 성장기록 발행의 피드백 태그하기에서 재태그 방지용 */
            isAdopted: boolean;
            id: number;
            questionId: number;
            questionTitle: string;
            questionContent: string;
            content: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        FeedbackListResponseDto: {
            success: boolean;
            data: components["schemas"]["FeedbackListItemDto"][];
        };
        RecentFeedbackItemDto: {
            category: components["schemas"]["RecordCategory"];
            submissionId: number;
            versionId: number;
            nickname: string;
            profileImageUrl: string;
            oneLineReview: string;
            /** @description 채택된 직군 질문에 대한 첫 번째 답변 본문 */
            content: string;
            projectId: number;
            projectName: string;
            /** @description presigned download URL */
            projectIconUrl: string;
        };
        RecentFeedbacksResponseDto: {
            success: boolean;
            data: components["schemas"]["RecentFeedbackItemDto"][];
        };
        FeedbackSubmissionAnswerDto: {
            category: components["schemas"]["RecordCategory"];
            imageUrls: string[];
            id: number;
            questionId: number;
            questionTitle: string;
            questionContent: string;
            content: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        FeedbackSubmissionDetailDto: {
            id: number;
            projectId: number;
            versionId: number;
            oneLineReview: string;
            author: components["schemas"]["FeedbackSubmissionAuthorDto"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            feedbacks: components["schemas"]["FeedbackSubmissionAnswerDto"][];
        };
        FeedbackSubmissionDetailResponseDto: {
            success: boolean;
            data: components["schemas"]["FeedbackSubmissionDetailDto"];
        };
        CreateProjectDto: {
            title: string;
            /** @enum {string} */
            type: "APP" | "WEB";
            /** @enum {string} */
            status: "Available" | "MVP" | "Ongoing" | "Hiring";
            oneLineDescription: string;
            description: string;
            category: ("HEALTHCARE" | "FINANCE" | "PUBLIC" | "COMMERCE" | "EDUCATION" | "ENTERTAINMENT" | "MOBILITY" | "ENERGY" | "REALESTATE" | "LIFESTYLE" | "PRODUCTIVITY" | "COMMUNITY" | "AI")[];
            contactPath: string;
            /** @enum {string} */
            leaderJobType: "Developer" | "Planner" | "Designer" | "Other";
            projectLink: string;
            iconKey: string;
            thumbnailKey: string;
            imageKeys: string[];
        };
        /** @enum {string} */
        ProjectType: "APP" | "WEB";
        /** @enum {string} */
        ProjectStatus: "Available" | "MVP" | "Ongoing" | "Hiring";
        /** @enum {string} */
        ProjectCategory: "HEALTHCARE" | "FINANCE" | "PUBLIC" | "COMMERCE" | "EDUCATION" | "ENTERTAINMENT" | "MOBILITY" | "ENERGY" | "REALESTATE" | "LIFESTYLE" | "PRODUCTIVITY" | "COMMUNITY" | "AI";
        ProjectResponseDto: {
            type: components["schemas"]["ProjectType"];
            status: components["schemas"]["ProjectStatus"];
            category: components["schemas"]["ProjectCategory"][];
            id: number;
            title: string;
            createdById: number;
            oneLineDescription: string;
            description: string;
            contactPath: string;
            projectLink: string;
            iconUrl: string;
            thumbnailUrl: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ProjectVersionCountDto: {
            versions: number;
        };
        ProjectListItemDto: {
            category: components["schemas"]["ProjectCategory"][];
            id: number;
            title: string;
            oneLineDescription: string;
            /** @description raw S3 key (presigned 변환은 P0-5 미해결) */
            thumbnailUrl: string;
            _count: components["schemas"]["ProjectVersionCountDto"];
            feedbackCount: number;
        };
        ProjectListResponseDto: {
            nextCursor: number | null;
            data: components["schemas"]["ProjectListItemDto"][];
            hasNextPage: boolean;
        };
        ProjectImageDto: {
            order: number;
            url: string;
        };
        ProjectMemberUserDto: {
            name: string;
            profileImageUrl: string;
        };
        ProjectMemberDto: {
            role: components["schemas"]["JobType"];
            id: number;
            userId: number;
            user: components["schemas"]["ProjectMemberUserDto"];
        };
        ProjectDetailResponseDto: {
            type: components["schemas"]["ProjectType"];
            status: components["schemas"]["ProjectStatus"];
            category: components["schemas"]["ProjectCategory"][];
            /** @description 요청자가 참여한 직군 (비로그인·비참여 시 null). 성장기록은 이 직군만 작성 가능 */
            myJobType: components["schemas"]["JobType"] | null;
            images: components["schemas"]["ProjectImageDto"][];
            projectRoles: components["schemas"]["ProjectMemberDto"][];
            /** @description 요청자가 이 프로젝트의 멤버인지 (비로그인 시 false) */
            isMyProject: boolean;
            id: number;
            title: string;
            createdById: number;
            oneLineDescription: string;
            description: string;
            contactPath: string;
            projectLink: string;
            iconUrl: string;
            thumbnailUrl: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateProjectDto: {
            title?: string;
            /** @enum {string} */
            type?: "APP" | "WEB";
            /** @enum {string} */
            status?: "Available" | "MVP" | "Ongoing" | "Hiring";
            oneLineDescription?: string;
            description?: string;
            category?: ("HEALTHCARE" | "FINANCE" | "PUBLIC" | "COMMERCE" | "EDUCATION" | "ENTERTAINMENT" | "MOBILITY" | "ENERGY" | "REALESTATE" | "LIFESTYLE" | "PRODUCTIVITY" | "COMMUNITY" | "AI")[];
            contactPath?: string;
            projectLink?: string;
            iconKey?: string;
            thumbnailKey?: string;
            imageKeys?: string[];
        };
        InviteCollaboratorDto: {
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: "Developer" | "Planner" | "Designer" | "Other";
        };
        ProjectRoleResponseDto: {
            role: components["schemas"]["JobType"];
            projectMemberRole: components["schemas"]["ProjectMemberRole"];
            id: number;
            userId: number;
            projectId: number;
        };
        ProjectVersionListItemDto: {
            id: number;
            version: string;
            /** Format: date-time */
            createdAt: string;
        };
        CreateGrowthRecordContentDto: {
            title: string;
            content: string;
            /** @default false */
            isDefault: boolean;
        };
        CreateGrowthRecordDto: {
            /** @enum {string} */
            category: "PLAN" | "DESIGN" | "DEVELOPMENT" | "GENERAL";
            contents: components["schemas"]["CreateGrowthRecordContentDto"][];
            /** @default [] */
            imageKeys: string[];
        };
        CreateFeedbackQuestionDto: {
            /** @enum {string} */
            category: "PLAN" | "DESIGN" | "DEVELOPMENT" | "GENERAL";
            content: string;
            /** @default false */
            isRequired: boolean;
        };
        TaggedSubmissionRefDto: {
            versionId: number;
            userId: number;
        };
        TaggedFeedbacksDto: {
            /** @enum {string} */
            category: "PLAN" | "DESIGN" | "DEVELOPMENT" | "GENERAL";
            submissions: components["schemas"]["TaggedSubmissionRefDto"][];
        };
        CreateVersionDto: {
            version: string;
            updateGoal: string;
            updateResults: string[];
            growthRecords: components["schemas"]["CreateGrowthRecordDto"][];
            feedbackQuestions: components["schemas"]["CreateFeedbackQuestionDto"][];
            taggedFeedbacks?: components["schemas"]["TaggedFeedbacksDto"][];
        };
        PublishedGrowthRecordContentDto: {
            id: number;
            growthRecordId: number;
            title: string;
            content: string;
            isDefault: boolean;
        };
        PublishedGrowthRecordImageDto: {
            id: number;
            growthRecordId: number;
            url: string;
            order: number;
            /** Format: date-time */
            createdAt: string;
        };
        PublishedGrowthRecordDto: {
            category: components["schemas"]["RecordCategory"];
            id: number;
            versionId: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            contents: components["schemas"]["PublishedGrowthRecordContentDto"][];
            images: components["schemas"]["PublishedGrowthRecordImageDto"][];
        };
        VersionFeedbackQuestionDto: {
            category: components["schemas"]["RecordCategory"];
            id: number;
            content: string;
            isRequired: boolean;
            order: number;
        };
        PublishVersionResponseDto: {
            /** Format: date-time */
            releasedAt: string | null;
            id: number;
            projectId: number;
            version: string;
            updateGoal: string;
            updateResults: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            growthRecords: components["schemas"]["PublishedGrowthRecordDto"][];
            feedbackQuestions: components["schemas"]["VersionFeedbackQuestionDto"][];
        };
        VersionDetailContentDto: {
            title: string;
            content: string;
            isDefault: boolean;
        };
        VersionDetailImageDto: {
            /** @description presigned download URL */
            url: string;
            order: number;
        };
        TaggedFeedbackAuthorDto: {
            role: components["schemas"]["JobType"] | null;
            name: string;
            profileImageUrl: string;
        };
        TaggedFeedbackDto: {
            /** @description 태그된 피드백 제출(submission) id */
            id: number;
            author: components["schemas"]["TaggedFeedbackAuthorDto"];
            /** @description 제출의 한 줄 평가(oneLineReview) */
            content: string;
        };
        VersionDetailGrowthRecordDto: {
            category: components["schemas"]["RecordCategory"];
            id: number;
            versionId: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            contents: components["schemas"]["VersionDetailContentDto"][];
            images: components["schemas"]["VersionDetailImageDto"][];
            taggedFeedbacks: components["schemas"]["TaggedFeedbackDto"][];
        };
        VersionDetailResponseDto: {
            /** Format: date-time */
            releasedAt: string | null;
            id: number;
            projectId: number;
            version: string;
            updateGoal: string;
            updateResults: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            growthRecords: components["schemas"]["VersionDetailGrowthRecordDto"][];
            feedbackQuestions: components["schemas"]["VersionFeedbackQuestionDto"][];
        };
        FeedbackTemplateDto: {
            category: components["schemas"]["RecordCategory"];
            questions: string[];
        };
        RecentGrowthRecordDto: {
            projectCategories: components["schemas"]["ProjectCategory"][];
            category: components["schemas"]["RecordCategory"];
            growthRecordId: number;
            versionId: number;
            projectId: number;
            projectName: string;
            /** @description presigned download URL */
            projectIconUrl: string;
            /** @description 해당 직군 성장기록의 첫 번째 content title */
            title: string;
            updateGoal: string;
            /** Format: date-time */
            releasedAt: string;
        };
        DraftUpdatedByDto: {
            id: number;
            name: string;
            profileImageUrl: string;
        };
        GrowthRecordDraftResponseDto: {
            category: components["schemas"]["RecordCategory"];
            /** @description FE 폼 스냅샷 (자유 형식 JSON — 발행 시점에만 정식 검증) */
            content: {
                [key: string]: unknown;
            };
            /** @description 마지막 수정자 (탈퇴 시 null) */
            updatedBy: components["schemas"]["DraftUpdatedByDto"] | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpsertDraftDto: {
            content: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseDto"];
                };
            };
        };
    };
    StorageController_checkHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BucketStatusResponseDto"];
                };
            };
        };
    };
    StorageController_getUploadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetUploadUrlDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadUrlResponseDto"];
                };
            };
        };
    };
    StorageController_getDownloadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadUrlResponseDto"];
                };
            };
        };
    };
    StorageController_deleteFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_checkIsNewUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserCheckResponseDto"];
                };
            };
        };
    };
    UserController_generateRandomNickname: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NicknameResponseDto"];
                };
            };
        };
    };
    UserController_onboarding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    UserController_getProfilePreviewByEmail: {
        parameters: {
            query: {
                /** @description 검색할 유저의 이메일 주소 */
                email: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfilePreviewResponseDto"];
                };
            };
        };
    };
    UserController_getOtherUserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OtherUserProfileResponseDto"];
                };
            };
        };
    };
    UserController_getOtherUserJoinedProjects: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MypageJoinedProjectListDto"][];
                };
            };
        };
    };
    MypageController_getMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyProfileResponseDto"];
                };
            };
        };
    };
    MypageController_updateMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MypageUpdateDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyProfileUpdateResponseDto"];
                };
            };
        };
    };
    MypageController_getMyJoinedProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MypageJoinedProjectListDto"][];
                };
            };
        };
    };
    MypageController_getMyFeedbacks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyFeedbackProjectsResponseDto"];
                };
            };
        };
    };
    FeedbackController_findFeedbacksForVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                versionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackListResponseDto"];
                };
            };
        };
    };
    FeedbackController_createFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                versionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFeedbackDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateFeedbackResponseDto"];
                };
            };
        };
    };
    FeedbackController_findAllQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                versionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackQuestionsResponseDto"];
                };
            };
        };
    };
    MyFeedbackController_getRecentFeedbacks: {
        parameters: {
            query?: {
                take?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecentFeedbacksResponseDto"];
                };
            };
        };
    };
    MyFeedbackController_findMyFeedbackProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyFeedbackProjectsResponseDto"];
                };
            };
        };
    };
    MyFeedbackController_findFeedbackSubmissionDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submissionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackSubmissionDetailResponseDto"];
                };
            };
        };
    };
    ProjectController_getProjects: {
        parameters: {
            query?: {
                search?: string;
                category?: "HEALTHCARE" | "FINANCE" | "PUBLIC" | "COMMERCE" | "EDUCATION" | "ENTERTAINMENT" | "MOBILITY" | "ENERGY" | "REALESTATE" | "LIFESTYLE" | "PRODUCTIVITY" | "COMMUNITY" | "AI";
                take?: number;
                cursor?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListResponseDto"];
                };
            };
        };
    };
    ProjectController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponseDto"];
                };
            };
        };
    };
    ProjectController_getMyProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListItemDto"][];
                };
            };
        };
    };
    ProjectController_getProjectById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetailResponseDto"];
                };
            };
        };
    };
    ProjectController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponseDto"];
                };
            };
        };
    };
    ProjectController_inviteCollaborator: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteCollaboratorDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRoleResponseDto"];
                };
            };
        };
    };
    ProjectController_getThumbnail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectController_getProjectVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectVersionListItemDto"][];
                };
            };
        };
    };
    GrowthRecordController_createVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVersionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishVersionResponseDto"];
                };
            };
        };
    };
    GrowthRecordController_getVersionDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionDetailResponseDto"];
                };
            };
        };
    };
    GrowthRecordTemplateController_getFeedbackTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackTemplateDto"][];
                };
            };
        };
    };
    GrowthRecordTemplateController_getRecentGrowthRecords: {
        parameters: {
            query?: {
                /** @description 최근 발행 버전 수 (버전당 4개 직군 카드가 반환됨) */
                take?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecentGrowthRecordDto"][];
                };
            };
        };
    };
    GrowthRecordDraftController_getDrafts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrowthRecordDraftResponseDto"][];
                };
            };
        };
    };
    GrowthRecordDraftController_getDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                category: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrowthRecordDraftResponseDto"];
                };
            };
        };
    };
    GrowthRecordDraftController_upsertDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                category: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertDraftDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrowthRecordDraftResponseDto"];
                };
            };
        };
    };
    GrowthRecordDraftController_deleteDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                category: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
