/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["StorageController_checkHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["StorageController_getUploadUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage/download-url/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["StorageController_getDownloadUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["StorageController_deleteFile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserController_checkIsNewUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/nickname": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserController_generateRandomNickname"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["UserController_onboarding"];
        trace?: never;
    };
    "/user/{userId}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserController_getUserProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProjectController_getProjects"];
        put?: never;
        post: operations["ProjectController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProjectController_getMyProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProjectController_getProjectById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project/{id}/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ProjectController_inviteCollaborator"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProjectController_getProjectVersions"];
        put?: never;
        post: operations["GrowthRecordController_createVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project/{id}/versions/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GrowthRecordController_getVersionDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/growth-records/feedback-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GrowthRecordTemplateController_getFeedbackTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project/{id}/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GrowthRecordDraftController_getDrafts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project/{id}/drafts/{category}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GrowthRecordDraftController_getDraft"];
        put: operations["GrowthRecordDraftController_upsertDraft"];
        post?: never;
        delete: operations["GrowthRecordDraftController_deleteDraft"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project/{projectId}/versions/{versionId}/feedbacks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["FeedbackController_createFeedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project/{projectId}/versions/{versionId}/feedbackQuestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FeedbackController_findAllQuestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedbacks/my/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MyFeedbackController_findMyFeedbackProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponseDto: Record<string, never>;
        BucketStatusResponseDto: {
            bucket: string;
            status: string;
            objectCount: number;
        };
        GetUploadUrlDto: Record<string, never>;
        UploadUrlResponseDto: {
            /** @description presigned upload URL (PUT 대상) */
            url: string;
            /** @description DB에 저장할 S3 object key */
            key: string;
        };
        DownloadUrlResponseDto: {
            /** @description presigned download URL */
            url: string;
        };
        UserCheckResponseDto: {
            /** @description 온보딩(jobType 설정) 미완료 여부 */
            isNewUser: boolean;
            nickname: string;
        };
        NicknameResponseDto: {
            nickname: string;
        };
        OnboardingDto: {
            /** @enum {string} */
            jobType: "Developer" | "Planner" | "Designer" | "Other";
            nickname: string;
        };
        /** @enum {string} */
        JobType: "Planner" | "Designer" | "Developer" | "Other";
        /** @enum {string} */
        UserRole: "Sprout" | "Seeder";
        UserResponseDto: {
            jobType: components["schemas"]["JobType"] | null;
            userRole: components["schemas"]["UserRole"];
            bio: string | null;
            id: number;
            name: string;
            email: string;
            emailVerified: boolean;
            profileImageUrl: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            ownedTicketCount: number;
            skills: string[];
            links: string[];
        };
        UserProfileResponseDto: {
            jobType: components["schemas"]["JobType"] | null;
            bio: string | null;
            id: number;
            name: string;
            profileImageUrl: string;
            skills: string[];
            links: string[];
        };
        CreateProjectDto: {
            title: string;
            /** @enum {string} */
            type: "APP" | "WEB";
            /** @enum {string} */
            status: "Available" | "MVP" | "Ongoing" | "Hiring";
            oneLineDescription: string;
            description: string;
            category: ("HEALTHCARE" | "FINANCE" | "PUBLIC" | "COMMERCE" | "EDUCATION" | "ENTERTAINMENT" | "MOBILITY" | "ENERGY" | "REALESTATE" | "LIFESTYLE" | "PRODUCTIVITY" | "COMMUNITY" | "AI")[];
            contactPath: string;
            /** @enum {string} */
            leaderJobType: "Developer" | "Planner" | "Designer" | "Other";
            projectLink: string;
            iconKey: string;
            thumbnailKey: string;
            imageKeys: string[];
        };
        /** @enum {string} */
        ProjectType: "APP" | "WEB";
        /** @enum {string} */
        ProjectStatus: "Available" | "MVP" | "Ongoing" | "Hiring";
        /** @enum {string} */
        ProjectCategory: "HEALTHCARE" | "FINANCE" | "PUBLIC" | "COMMERCE" | "EDUCATION" | "ENTERTAINMENT" | "MOBILITY" | "ENERGY" | "REALESTATE" | "LIFESTYLE" | "PRODUCTIVITY" | "COMMUNITY" | "AI";
        ProjectResponseDto: {
            type: components["schemas"]["ProjectType"];
            status: components["schemas"]["ProjectStatus"];
            category: components["schemas"]["ProjectCategory"][];
            id: number;
            title: string;
            createdById: number;
            oneLineDescription: string;
            description: string;
            contactPath: string;
            projectLink: string;
            iconUrl: string;
            thumbnailUrl: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ProjectVersionCountDto: {
            versions: number;
        };
        ProjectListItemDto: {
            category: components["schemas"]["ProjectCategory"][];
            id: number;
            title: string;
            oneLineDescription: string;
            /** @description raw S3 key (presigned 변환은 P0-5 미해결) */
            thumbnailUrl: string;
            _count: components["schemas"]["ProjectVersionCountDto"];
            feedbackCount: number;
        };
        ProjectListResponseDto: {
            nextCursor: number | null;
            data: components["schemas"]["ProjectListItemDto"][];
            hasNextPage: boolean;
        };
        ProjectImageDto: {
            order: number;
            url: string;
        };
        ProjectMemberUserDto: {
            name: string;
            profileImageUrl: string;
        };
        ProjectMemberDto: {
            role: components["schemas"]["JobType"];
            id: number;
            user: components["schemas"]["ProjectMemberUserDto"];
        };
        ProjectDetailResponseDto: {
            type: components["schemas"]["ProjectType"];
            status: components["schemas"]["ProjectStatus"];
            category: components["schemas"]["ProjectCategory"][];
            id: number;
            title: string;
            createdById: number;
            oneLineDescription: string;
            description: string;
            contactPath: string;
            projectLink: string;
            iconUrl: string;
            thumbnailUrl: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            images: components["schemas"]["ProjectImageDto"][];
            projectRoles: components["schemas"]["ProjectMemberDto"][];
            /** @description 요청자가 이 프로젝트의 멤버인지 (비로그인 시 false) */
            isMyProject: boolean;
        };
        InviteCollaboratorDto: {
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: "Developer" | "Planner" | "Designer" | "Other";
        };
        /** @enum {string} */
        ProjectMemberRole: "Lead" | "TeamLeader" | "TeamMember";
        ProjectRoleResponseDto: {
            role: components["schemas"]["JobType"];
            projectMemberRole: components["schemas"]["ProjectMemberRole"];
            id: number;
            userId: number;
            projectId: number;
        };
        ProjectVersionListItemDto: {
            id: number;
            version: string;
            /** Format: date-time */
            createdAt: string;
        };
        CreateGrowthRecordContentDto: {
            title: string;
            content: string;
            /** @default false */
            isDefault: boolean;
        };
        CreateGrowthRecordDto: {
            /** @enum {string} */
            category: "PLAN" | "DESIGN" | "DEVELOPMENT" | "GENERAL";
            contents: components["schemas"]["CreateGrowthRecordContentDto"][];
            /** @default [] */
            imageKeys: string[];
        };
        CreateFeedbackQuestionDto: {
            /** @enum {string} */
            category: "PLAN" | "DESIGN" | "DEVELOPMENT" | "GENERAL";
            content: string;
            /** @default false */
            isRequired: boolean;
        };
        TaggedFeedbacksDto: {
            /** @enum {string} */
            category: "PLAN" | "DESIGN" | "DEVELOPMENT" | "GENERAL";
            submissionIds: number[];
        };
        CreateVersionDto: {
            version: string;
            updateGoal: string;
            updateResults: string[];
            growthRecords: components["schemas"]["CreateGrowthRecordDto"][];
            feedbackQuestions: components["schemas"]["CreateFeedbackQuestionDto"][];
            taggedFeedbacks?: components["schemas"]["TaggedFeedbacksDto"][];
        };
        /** @enum {string} */
        RecordCategory: "PLAN" | "DESIGN" | "DEVELOPMENT" | "GENERAL";
        PublishedGrowthRecordContentDto: {
            id: number;
            growthRecordId: number;
            title: string;
            content: string;
            isDefault: boolean;
        };
        PublishedGrowthRecordImageDto: {
            id: number;
            growthRecordId: number;
            url: string;
            order: number;
            /** Format: date-time */
            createdAt: string;
        };
        PublishedGrowthRecordDto: {
            category: components["schemas"]["RecordCategory"];
            id: number;
            versionId: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            contents: components["schemas"]["PublishedGrowthRecordContentDto"][];
            images: components["schemas"]["PublishedGrowthRecordImageDto"][];
        };
        VersionFeedbackQuestionDto: {
            category: components["schemas"]["RecordCategory"];
            id: number;
            content: string;
            isRequired: boolean;
            order: number;
        };
        PublishVersionResponseDto: {
            /** Format: date-time */
            releasedAt: string | null;
            id: number;
            projectId: number;
            version: string;
            updateGoal: string;
            updateResults: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            growthRecords: components["schemas"]["PublishedGrowthRecordDto"][];
            feedbackQuestions: components["schemas"]["VersionFeedbackQuestionDto"][];
        };
        VersionDetailContentDto: {
            title: string;
            content: string;
            isDefault: boolean;
        };
        VersionDetailImageDto: {
            /** @description presigned download URL */
            url: string;
            order: number;
        };
        TaggedFeedbackAuthorDto: {
            role: components["schemas"]["JobType"] | null;
            name: string;
            profileImageUrl: string;
        };
        TaggedFeedbackDto: {
            /** @description 태그된 피드백 제출(submission) id */
            id: number;
            author: components["schemas"]["TaggedFeedbackAuthorDto"];
            /** @description 제출의 한 줄 평가(oneLineReview) */
            content: string;
        };
        VersionDetailGrowthRecordDto: {
            category: components["schemas"]["RecordCategory"];
            id: number;
            versionId: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            contents: components["schemas"]["VersionDetailContentDto"][];
            images: components["schemas"]["VersionDetailImageDto"][];
            taggedFeedbacks: components["schemas"]["TaggedFeedbackDto"][];
        };
        VersionDetailResponseDto: {
            /** Format: date-time */
            releasedAt: string | null;
            id: number;
            projectId: number;
            version: string;
            updateGoal: string;
            updateResults: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            growthRecords: components["schemas"]["VersionDetailGrowthRecordDto"][];
            feedbackQuestions: components["schemas"]["VersionFeedbackQuestionDto"][];
        };
        FeedbackTemplateDto: {
            category: components["schemas"]["RecordCategory"];
            questions: string[];
        };
        DraftUpdatedByDto: {
            id: number;
            name: string;
            profileImageUrl: string;
        };
        GrowthRecordDraftResponseDto: {
            category: components["schemas"]["RecordCategory"];
            /** @description FE 폼 스냅샷 (자유 형식 JSON — 발행 시점에만 정식 검증) */
            content: {
                [key: string]: unknown;
            };
            /** @description 마지막 수정자 (탈퇴 시 null) */
            updatedBy: components["schemas"]["DraftUpdatedByDto"] | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpsertDraftDto: {
            content: {
                [key: string]: unknown;
            };
        };
        FeedbackItemDto: {
            questionId: number;
            content: string;
            imageUrl?: string;
            imageUrls?: string[];
        };
        CreateFeedbackDto: {
            oneLineReview: string;
            feedbacks: components["schemas"]["FeedbackItemDto"][];
        };
        CreatedFeedbackDto: {
            imageUrl: string | null;
            imageUrls: string[];
            id: number;
            questionId: number;
            versionId: number;
            userId: number;
            content: string;
            /** Format: date-time */
            createdAt: string;
        };
        CreateFeedbackDataDto: {
            submittedCount: number;
            feedbacks: components["schemas"]["CreatedFeedbackDto"][];
        };
        CreateFeedbackResponseDto: {
            success: boolean;
            data: components["schemas"]["CreateFeedbackDataDto"];
        };
        FeedbackQuestionItemDto: {
            category: components["schemas"]["RecordCategory"];
            id: number;
            title: string;
            description: string;
            order: number;
            required: boolean;
        };
        FeedbackQuestionsResponseDto: {
            success: boolean;
            data: components["schemas"]["FeedbackQuestionItemDto"][];
        };
        MyFeedbackProjectItemDto: {
            submissionId: number;
            projectId: number;
            projectTitle: string;
            projectThumbnailUrl: string;
            oneLineDescription: string;
            isAdopted: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        MyFeedbackProjectsResponseDto: {
            success: boolean;
            data: components["schemas"]["MyFeedbackProjectItemDto"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseDto"];
                };
            };
        };
    };
    StorageController_checkHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BucketStatusResponseDto"];
                };
            };
        };
    };
    StorageController_getUploadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetUploadUrlDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadUrlResponseDto"];
                };
            };
        };
    };
    StorageController_getDownloadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadUrlResponseDto"];
                };
            };
        };
    };
    StorageController_deleteFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_checkIsNewUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserCheckResponseDto"];
                };
            };
        };
    };
    UserController_generateRandomNickname: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NicknameResponseDto"];
                };
            };
        };
    };
    UserController_onboarding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    UserController_getUserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponseDto"];
                };
            };
        };
    };
    ProjectController_getProjects: {
        parameters: {
            query?: {
                search?: string;
                category?: "HEALTHCARE" | "FINANCE" | "PUBLIC" | "COMMERCE" | "EDUCATION" | "ENTERTAINMENT" | "MOBILITY" | "ENERGY" | "REALESTATE" | "LIFESTYLE" | "PRODUCTIVITY" | "COMMUNITY" | "AI";
                take?: number;
                cursor?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListResponseDto"];
                };
            };
        };
    };
    ProjectController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponseDto"];
                };
            };
        };
    };
    ProjectController_getMyProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListItemDto"][];
                };
            };
        };
    };
    ProjectController_getProjectById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetailResponseDto"];
                };
            };
        };
    };
    ProjectController_inviteCollaborator: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteCollaboratorDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRoleResponseDto"];
                };
            };
        };
    };
    ProjectController_getProjectVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectVersionListItemDto"][];
                };
            };
        };
    };
    GrowthRecordController_createVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVersionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishVersionResponseDto"];
                };
            };
        };
    };
    GrowthRecordController_getVersionDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionDetailResponseDto"];
                };
            };
        };
    };
    GrowthRecordTemplateController_getFeedbackTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackTemplateDto"][];
                };
            };
        };
    };
    GrowthRecordDraftController_getDrafts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrowthRecordDraftResponseDto"][];
                };
            };
        };
    };
    GrowthRecordDraftController_getDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                category: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrowthRecordDraftResponseDto"];
                };
            };
        };
    };
    GrowthRecordDraftController_upsertDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                category: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertDraftDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrowthRecordDraftResponseDto"];
                };
            };
        };
    };
    GrowthRecordDraftController_deleteDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                category: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FeedbackController_createFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                versionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFeedbackDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateFeedbackResponseDto"];
                };
            };
        };
    };
    FeedbackController_findAllQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                versionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackQuestionsResponseDto"];
                };
            };
        };
    };
    MyFeedbackController_findMyFeedbackProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyFeedbackProjectsResponseDto"];
                };
            };
        };
    };
}
