apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proseed-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/skkuding/proseed
    targetRevision: main
    path: infra/k8s/argocd/applications
    directory:
      recurse: true
      exclude: 'proseed-root.yaml'
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
