apiVersion: v1
kind: ConfigMap
metadata:
  name: web-env
data:
  NEXT_URL: 'https://proseednow.com'
  MEDIA_BUCKET_NAME: 'proseed-media'
  OTEL_EXPORTER_OTLP_ENDPOINT: 'https://otel.proseednow.com'
  INTERNAL_API_URL: 'http://api-server.proseed.svc.cluster.local:4000/api'
