---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proseed-aws-credentials
  namespace: proseed-stage
spec:
  encryptedData:
    aws_access_key_id: AgAUpWwuY6yA131yjBlEmXnm+Q1xslwnOeByEfGgqL2afhXHcstlT5g8wkMbtuDBFS07TPQQSsk389ROKuV8gXwqk5lY9YHC8GBQjDJRw/ihxfm/5blQ+EJbnbKb57eRtL3TIsejO/izzQlUG16tnOVvnSgn78gTTOmWD/hHDbbcnWTBDdAPAvTe3ZHEZDSXh3MaUKh698qxsacwUYEniQ5y1UAHjJX2101yvtjFtwgQ9Fgts/2MqzqBDe/c6xDHJTsJcl0fIciorWQcGz3KNmu00ucl43gtQfHtfr4M9ybIsgGdPk+l84g8+Caz9Ey9qQDzaqMLHMdK3Kw/AC8yhM+rm6pmq8lYTYxe7vjj+4fAVZCkIG6+g1Ut18gZl70VzgPYBY2vtoVpTxrfO2OfMEbpxOHecTXwo05Q/rS7JmMSXmYpHtY9krZH5W838HzAkWnLav9OC/THw23LalITfI2ceqktHHSwOec+9q79EDHY/o1EYXTHurfN2pTS51dBW2g+BKElJh+dcV0NxsnotV3Rv3JwCMNKb8jQInbmvvh1JlIAv70r4k+kXdfo6ih4KbG5Pga346H8yiB74oMbp+kJ+kx2Kw2Ckt6WcbO0bvnWZxB7QM9SpFwwI0sQU1YsdKV9CJAQeVt9i2ah1lUrXZsTrmifUar0fKOM2cngQLt8fZ2+xWKnsXtUhThkmg+fPrZ9fqAkcUC4faBxKp6y73YCAgrk1Q==
    aws_secret_access_key: AgB8hhHRkLW6J/iLKW6qGQFCzgKxm/Xa4HNps9PeeJtLgg6WyBPVmWrhdDss4WvLn4v6dYncAa9xEFm6FtEkZiOFx3MXsYGJxNYQ+PS082DRWJQ628XGut6oyJGoTCVjrICYKaaa7VHnuxfX5cSCLpKhHKpALbGLjkENJdK82Pz7rACSaszVD49a6YVV2j29F105oC7nQXKWRtys3tzSoupTTTAZKqji/LJI1id8/ydNO0QmiAghbsOfX1LRjwDP0HBDQqM/MHz7OE5ivyJ773/M19YdnwAykEJ/umppS+IKqje/N+F+2jP8bJZ4JRrylufY6ZcsgO6sVfkm5RNuwlt2Dns3nuAVlha+gOSSo919EWGyPMf9j5d3sJFVVkuoRIH5gxnDBRujUu+LHdMd9UlIKeJmitu9mKUoTmIpgGUlavhQWbz2AC4+jx+tbi3uHO1OvIxQljYT9J0ji0TxpQ0Kh5s2gbo0TGnP/rDtGqkT3nr/EcH2ISdSRcDtoKglbkE2IX5cAWGU5QSrofYjeOFWQ6Sv2m8l+UaUwSQ4oYtykH36KEMjXhj3uOfdhfkjOF/ZsMuD7AYHHfBBP/MoLtfTwp71gvHLyqUzeRHRywhFCCQPmc0ljvujHG/wuqcQq9+HyJhU3msQw4fv+UVuISa+z9V3zJ1kAEoc9OLJKf92OQyt2voP2FzIBxJ7zbSUlbblWExDWYLB+QYvWJ/R4Iy8kLtI7ktS0pF7FFDgZABq0/cbdNXpJclq
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: '-1'
      name: proseed-aws-credentials
      namespace: proseed-stage
