apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: proseed-stage

resources:
  - ../../base
  - aws-credentials.yaml
  - oauth-credentials.yaml

patches:
  - path: configmap-patch.yaml
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: api-server-ingress
  - path: migration-patch.yaml

images:
  - name: ghcr.io/skkuding/proseed/api
    newTag: stage
